### ISSUE TITLE
Can you please generate official Docker container.

### ISSUE THREAD

**Issue by piv-pav** [ruecat/ollama-telegram#14]
First of all, I really appreciate your excellent work and the provided Dockerfile for a smoother setup. 

Would you please consider to provide an official Docker image on Docker Hub or as GitHub Package? This would greatly benefit users who want to easily run your bot without building container manually. Thank you for your dedication, and I hope to see more of your excellent work.

**Comment by ShrirajHegde** [comment]
Just run the docker compose command with

`docker compose up -d --build`

If you have the base layers in cache, it takes 2–3 seconds to build and create the container, not any slower than using a prebuilt container.

**Comment by piv-pav** [comment]
Thanks for implementing that so rapidly. I understand that anyone can build the image using Dockerfile anytime, but having official image solves the burden of updating the bot to the latest version using something like `watchtower`, and triggering container updates based on the commits in the official repository is the better option than implementing that using cronjob with regular pulls.

Thanks again for your effort.
