### ISSUE TITLE
"Typing..." indicator disappears after first update of the reply

### ISSUE THREAD

**Issue by hynet-mel** [ruecat/ollama-telegram#20]
I've noticed that the "Typing..." action status indicator on the bot disappears right after the first time it receives the first part of the message. I think this might be a bug?
I think it might be useful to have that present during the entire duration of the reply generation as a indicator that the model is still generating a reply. But at this time, after receiving the first chunk of the reply the indicator disappears

**Comment by ruecat** [comment]
Solved in new commit, but there's a known bug with supergroups. 
Will fix it in 2-3 days.
