### ISSUE TITLE
feature request: "processing.." message

### ISSUE THREAD

**Issue by hhenne1** [ruecat/ollama-telegram#21]
Hi,
thanks for your great work. Works like a charm.
One thing though.. My Ollama instance is not permanently used, so most of the time the model is unloaded.
It is loading the model on request correctly, but the initial message takes quite some time while the model is loading.
It would be nice (and less confusing for my friends) if, while this is happening, some sort of "processing.." or "loading" message is shown.
Just a thought, if it doesn't fit your vision, that's perfectly fine too.
Thanks again

**Comment by ruecat** [comment]
It was a thing in beta, but deprecated because we have "typing" indicator which shows that response being generated. No need to add it back again.
