### ISSUE TITLE
Telegram server says - Bad Request: can't parse entities: Can't find end of Bold entity at byte offset

### ISSUE THREAD

**Issue by Antoniofiliona** [ruecat/ollama-telegram#27]
I've received this error a few times during the ollama's mixtral response. 

    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of Bold entity at byte offset 603

**Comment by lemassykoi** [comment]
> I have a similar issue with LLama3: `aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of Bold entity at byte offset 1455`
> 
> Found out a couple of things which may be related and help with this issue: ![SendGithub](https://private-user-images.githubusercontent.com/25671679/325290797-9a258036-7120-4c56-93cb-af50f02e5904.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0Mzg2MjYsIm5iZiI6MTcxNTQzODMyNiwicGF0aCI6Ii8yNTY3MTY3OS8zMjUyOTA3OTctOWEyNTgwMzYtNzEyMC00YzU2LTkzY2ItYWY1MGYwMmU1OTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE0Mzg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ODRmYTNlMGY5NzBiYjdlMWQzOWNjYTQzZjllNWY5ZjU3MTNjMjAzZDRlZjhjMmM0ZjU2NDE0MTU3YmQwMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Oq7RIJAyGfixE7FovCmYHFIoMxQQ69wykeZ2WKh_BI0) ![image](https://private-user-images.githubusercontent.com/25671679/325290845-820979f8-3072-4615-8b54-3a45b561a908.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0Mzg2MjYsIm5iZiI6MTcxNTQzODMyNiwicGF0aCI6Ii8yNTY3MTY3OS8zMjUyOTA4NDUtODIwOTc5ZjgtMzA3Mi00NjE1LThiNTQtM2E0NWI1NjFhOTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE0Mzg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMjMzZWI5ZDg0ZjRmMDAzZDY3YjZmMjE2M2Y5NGQyYTdmZmIwMjZjMDFlNzIxM2U5YzA1ODZlZjIyNjdmMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1IsZuUNGRx7Twv9I13iT5O5koHhXagbcL8-i9MGMxO0)
> 
> likely cause is that it does not include the asterisk character * in the list of characters to escape (escape_chars). The fix should be something like this:
> 
> ```
> def md_autofixer(text: str) -> str:
>     # In MarkdownV2, these characters must be escaped: _ * [ ] ( ) ~ ` > # + - = | { } . !
>     escape_chars = r"_*[]()~>#+-=|{}.!"    # Use a backslash to escape special characters
>     return "".join("\\" + char if char in escape_chars else char for char in text)
> ```

Hi, I changed as you suggested, but now, there are 2 extra stars at the end :
![image](https://github.com/ruecat/ollama-telegram/assets/16377344/bec4fc97-a737-45a1-bd52-29a1e8b2cde8)

then, not sure it's the correct solution

**Comment by amaannt** [comment]
I agree that it might not be the correct solution. But it fixed the error that caused the crashes and stopped the bot for me. I hope the original contributers can look into this specifically

**Comment by ruecat** [comment]
Fixed (MD regression)
