### ISSUE TITLE
feature request: integration of group chats

### ISSUE THREAD

**Issue by hhenne1** [ruecat/ollama-telegram#30]
(again... love your work so far, slightly sorry for opening this)
The current version allows the bot to be added to group chats, but responds with "access denied" to all users not individually added to the config. 
It would be nice to be able to add group IDs. (since my few friends do not know what their id is and are not inclined to find out and/or tell)
Since groups usually contain non-bot related chats, it would also be nice if within those groups it would only react to a specific /something or @bot message, instead of reacting to every potentially unrelated message.

If this is already on your agenda, or has been ignored for some reason, I apologize.

**Comment by ruecat** [comment]
Works in our new update.
