### ISSUE TITLE
bot not replying 400 bad api request?

### ISSUE THREAD

**Issue by mebbeh** [ruecat/ollama-telegram#33]
Hello, I think I am so close to getting this running, and love the idea of the potential of this interface you've made!
I'm on windows and have installed without docker. I have pulled a model, and run ollama using ollama serve.
i've set my .env file up as instructed, i have the bot token in place, i have my user ID under ADMIN_IDS and USER_IDS, i have the OLLAMA_BASE_URL set to localhost.
![Screenshot 2024-02-23 153451](https://github.com/ruecat/ollama-telegram/assets/161054296/78edf0d1-d58c-4bf1-97ee-556d4d399659)

I can see the messages come in and ollama-telegram says it has been "handled", the bot is "typing" in telegram, but ultimately I do not receive a reply.
![Screenshot 2024-02-23 153655](https://github.com/ruecat/ollama-telegram/assets/161054296/727937c6-6cd1-4190-ae38-80357859a8f2)

When i look over at the ollama terminal I see the 400 error:
![Screenshot 2024-02-23 153352](https://github.com/ruecat/ollama-telegram/assets/161054296/8636270e-e681-40ce-92f8-350e2256e53c)

Thank you for your help

**Comment by cisasteelersfan** [comment]
I was having the exact same problem. I was able to resolve it by downgrading my ollama-server version - something must have changed in the API. (I'm currently using ollama:0.1.19, and it's working.)

**Comment by cisasteelersfan** [comment]
Well, after playing around some more, maybe it's not so simple. I seem to get a 400 Bad Request in some circumstances, and 404 Not found when specify a model that doesn't exist?
