### ISSUE TITLE
Bot doesn’t give reply on telegram 

### ISSUE THREAD

**Issue by drmetro09** [ruecat/ollama-telegram#4]
Bot doesn’t reply when i send message from telegram i can see the logs they are goodwhat could be the problem

**Comment by ruecat** [comment]
Have you tried to launch OllamaAPI? It should be running in the background.

**Comment by aarvndhNG** [comment]
![Screenshot_20231221-141348](https://github.com/ruecat/ollama-telegram/assets/107058543/9e6e325d-f89a-4dd5-ac0e-b1266c17fe8a)
Can you help me with this

**Comment by ruecat** [comment]
Edit .env and put your telegram ID.

**Comment by aarvndhNG** [comment]
I did put the my id

**Comment by ruecat** [comment]
Did you follow what is in .env.example?
Also, your telegram ID may be incorrect. Try to put it like this:
```
ADMIN_IDS=1213753840
USER_IDS=1213753840
```

**Comment by ruecat** [comment]
I will add error handlers soon, it will be more easy to understand what's wrong

**Comment by aarvndhNG** [comment]
> I will add error handlers soon, it will be more easy to understand what's wrong

Okay I'll try again
