### ISSUE TITLE
Timeout Issues When Running on RPi

### ISSUE THREAD

**Issue by sxingxian** [ruecat/ollama-telegram#47]
I'm running it on Raspberry pi 4, which has low compute power, hence, it will take sometime to generate out the responses. 
Is there a way to increase the timeout via env variable (or something simple), so that it will not hit the timeout error? 

`Traceback (most recent call last):
  File "/code/run.py", line 194, in ollama_request
    async for response_data in generate(payload, modelname, prompt):
  File "/code/func/functions.py", line 50, in generate
    async for chunk in response.content:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 44, in __anext__
    rv = await self.read_func()
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 307, in readline
    return await self.readuntil()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 341, in readuntil
    await self._wait("readuntil")
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 301, in _wait
    with self._timer:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError`

**Comment by sxingxian** [comment]
After the recent timeout implementations: 

[OllamaAPI-ERR] CAUGHT FAULT!
Traceback (most recent call last):
  File "/code/run.py", line 229, in ollama_request
    async for response_data in generate(payload, modelname, prompt):
  File "/code/func/interactions.py", line 35, in generate
    timeout = ClientTimeout(total=timeout)
                                  ^^^^^^^
UnboundLocalError: cannot access local variable 'timeout' where it is not associated with a value

**Comment by pashagta555** [comment]
The same error

**Comment by hhenne1** [comment]
same error here.. either with timeout or TIMEOUT.. inspect on docker shows that the env-variable is read/set correctly

**Comment by lediszep** [comment]
```
[OllamaAPI-ERR] CAUGHT FAULT!
Traceback (most recent call last):
  File "/code/run.py", line 229, in ollama_request
    async for response_data in generate(payload, modelname, prompt):
  File "/code/func/interactions.py", line 35, in generate
    timeout = ClientTimeout(total=timeout)
                                  ^^^^^^^
UnboundLocalError: cannot access local variable 'timeout' where it is not associated with a value

```
Same on unRAID docker

**Comment by ruecat** [comment]
Update docker image, should work now

**Comment by nierto** [comment]
@ruecat  Sorry, I did not update the docker Image as well! 
@sxingxian you can set the TIMEOUT variable as per your demands. I have it on the default value (3000) which is 50 minutes.

**Comment by pashagta555** [comment]
> @ruecat Sorry, I did not update the docker Image as well! @sxingxian you can set the TIMEOUT variable as per your demands. I have it on the default value (3000) which is 50 minutes.

I am running it via raspberry pi os on raspberry pi 5 and got same error. TIMEOUT variable is set to default value (3000). how I can fix it? May be  I must to set this variable via another file? can u help me with it?

**Comment by hhenne1** [comment]
my docker version works fine now (aside from issue #50) . thx ♥

**Comment by ruecat** [comment]
Fixed in new version.
